# Generated by Django 6.0 on 2026-02-10 20:04

import django.db.models.deletion
import src.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=src.utils.helpers.random_token,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("paymentStatus", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                (
                    "paymentMethod",
                    models.CharField(
                        choices=[("bank", "bank"), ("momo", "momo")],
                        default="momo",
                        max_length=150,
                    ),
                ),
                ("paymentReference", models.CharField(max_length=150)),
                (
                    "confirmedBy",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "createdBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                (
                    "updatedBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now=True)),
                ("updatedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
    ]
