# Generated by Django 6.0 on 2026-02-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
