# Generated by Django 6.0 on 2026-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="status",
            new_name="paymentStatus",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="paymentId",
        ),
        migrations.AddField(
            model_name="payment",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
