# Generated by Django 6.0 on 2026-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_paid_at_payment_receipt_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="paystacktransactionreference",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="paystacktransactionreference",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
