# Generated by Django 6.0 on 2026-02-14 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paystacktransactionreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="paystacktransactionreference",
            name="paymentLink",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
