# Generated by Django 6.0 on 2026-02-15 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_customer"),
        ("payments", "0003_paystacktransactionreference_paymentlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paystacktransactionreference",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paystackTrxRefObj",
                to="orders.order",
            ),
        ),
    ]
