# Generated by Django 6.0 on 2026-03-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_createdat_alter_payment_updatedat_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paystacktransactionreference",
            options={
                "ordering": ["-createdAt"],
                "verbose_name_plural": "Paystack Transaction Ref",
            },
        ),
    ]
