# Generated by Django 6.0 on 2026-01-30 06:33

import src.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=src.utils.helpers.random_token, editable=False, primary_key=True, serialize=False)),
                ('notificationId', models.CharField(default=src.utils.helpers.random_token, editable=False)),
                ('notificationType', models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('whatsapp', 'whatsapp')], default='', max_length=255)),
                ('topic', models.CharField(max_length=255, null=True)),
                ('message', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('createdBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('updatedBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
