# Generated by Django 6.0 on 2026-02-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='status',
            new_name='processed',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notificationId',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='topic',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
