# Generated by Django 6.0 on 2026-02-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_status_notification_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notificationType',
        ),
    ]
