# Generated by Django 6.0 on 2026-03-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-createdAt"], "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="customer",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
