# Generated by Django 6.0 on 2026-02-14 18:08

import src.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=src.utils.helpers.random_token,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.EmailField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "Male"), ("f", "Female")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "createdBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                (
                    "updatedBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now=True)),
                ("updatedAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
