# Generated by Django 6.0 on 2026-01-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdAat',
            new_name='createdAt',
        ),
    ]
