# Generated by Django 6.0 on 2026-01-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('biker', 'biker'), ('customer', 'customer'), ('vendor', 'vendor'), ('office_agent', 'office_agent')], default='customer', max_length=150, null=True),
        ),
    ]
