services:
  web:
    build: .
    image: lingo_app:latest
    command: gunicorn --bind 0.0.0.0:8001 --worker-class gevent --workers 6 api.wsgi --log-level debug --timeout 0
    restart: always
    expose:
      - "8001"
    volumes:
      - lingo_static_files:/app/src/static
    depends_on:
        - redis
        - db
    environment:
      - VIRTUAL_HOST=lingo.service4gh.com
      - VIRTUAL_PORT=8001
      - LETSENCRYPT_HOST=lingo.service4gh.com
      - LETSENCRYPT_EMAIL=mohammedyiwere@gmail.com
      - REDIS_PUBSUB_HOST=redis      
      - REDIS_PUBSUB_DB_INDEX=2
    networks:
      - proxy-tier
      - backend-tier
  db:
    image: postgres:16
    restart: always
    volumes:
      - lingo_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend-tier
    
  celery:
    build: .
    image: lingo_app:latest
    command: celery -A api worker -l info --concurrency=4 --max-tasks-per-child=100
    restart: always
    depends_on:
      - redis
      - db
    networks:
      - backend-tier
  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - backend-tier
networks:
  proxy-tier:
    external: true
    name: fulstack_default
  backend-tier:
    driver: bridge
volumes:
  lingo_db:
  lingo_static_files:

#GITOPS_HASH: 0000000
