# Generated by Django 6.0 on 2026-03-02 18:13

import src.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=src.utils.helpers.random_token,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reportId",
                    models.CharField(
                        default=src.utils.helpers.random_token, editable=False
                    ),
                ),
                ("reportName", models.CharField(max_length=255)),
                (
                    "reportType",
                    models.CharField(
                        choices=[("vendor", "vendor"), ("order", "order")],
                        max_length=255,
                    ),
                ),
                (
                    "reportScope",
                    models.CharField(
                        choices=[("all", "All"), ("agent", "By Agent")], max_length=255
                    ),
                ),
                ("reportNotes", models.TextField(blank=True, null=True)),
                (
                    "createdBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                (
                    "updatedBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
