# Generated by Django 6.0 on 2026-03-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="exportFormat",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("excel", "Excel")],
                default="pdf",
                max_length=20,
            ),
        ),
    ]
