# Generated by Django 6.0 on 2026-01-30 06:33

import src.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biker',
            fields=[
                ('id', models.CharField(default=src.utils.helpers.random_token, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('totalTrips', models.IntegerField(blank=True, default=0, null=True)),
                ('createdBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('updatedBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(default=src.utils.helpers.random_token, editable=False, primary_key=True, serialize=False)),
                ('vehicleType', models.CharField(blank=True, choices=[('car', 'car'), ('motorbike', 'motorbike')], default='motorbike', max_length=20, null=True)),
                ('licensePlate', models.CharField(blank=True, max_length=20, null=True)),
                ('registered', models.BooleanField(blank=True, default=False, null=True)),
                ('createdBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('updatedBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
