# Generated by Django 6.0 on 2026-02-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='biker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikers.biker'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleType',
            field=models.CharField(blank=True, choices=[('car', 'car'), ('bike', 'bike')], default='bike', max_length=20, null=True),
        ),
    ]
