# Generated by Django 6.0 on 2026-01-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='licensePlate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleType',
            field=models.CharField(blank=True, choices=[('0', 'car'), ('1', 'motorbike')], default='motorbike', max_length=20, null=True),
        ),
    ]
