# Generated by Django 6.0 on 2026-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biker",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="biker",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
