# Generated by Django 6.0 on 2026-01-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikers', '0003_alter_vehicle_licenseplate_alter_vehicle_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleType',
            field=models.CharField(blank=True, choices=[('car', 'car'), ('motorbike', 'motorbike')], default='motorbike', max_length=20, null=True),
        ),
    ]
