# Generated by Django 6.0 on 2026-03-09 14:36

import src.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikers", "0003_alter_biker_createdat_alter_biker_updatedat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=src.utils.helpers.random_token,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deliveryId",
                    models.CharField(
                        default=src.utils.helpers.random_token, editable=False
                    ),
                ),
                (
                    "orderId",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "deliveryCompletionNote",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dispatchService",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "createdBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                (
                    "updatedBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
