# Generated by Django 6.0 on 2026-02-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikers', '0003_alter_vehicle_biker_alter_vehicle_vehicletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='biker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikers.biker'),
        ),
    ]
