# Generated by Django 6.0 on 2026-03-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bikers", "0004_delivery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="deliveryId",
            new_name="deliveryTokenId",
        ),
    ]
