# Generated by Django 6.0 on 2026-03-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikers", "0005_rename_deliveryid_delivery_deliverytokenid"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="vendorNotified",
            field=models.BooleanField(default=False),
        ),
    ]
