# Generated by Django 6.0 on 2026-03-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikers", "0006_delivery_vendornotified"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="dispatchServiceDeliveryType",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="dispatchServiceTrackingNumber",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
