# Generated by Django 6.0 on 2026-03-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikers", "0007_delivery_dispatchservicedeliverytype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="dispatchServiceTrackingNumber",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
