# Generated by Django 6.0 on 2026-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikers", "0008_alter_delivery_dispatchservicetrackingnumber"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["-createdAt"],
                "verbose_name_plural": "Order Deliveries",
            },
        ),
        migrations.AddField(
            model_name="delivery",
            name="dispatchAssigned",
            field=models.BooleanField(default=False),
        ),
    ]
