# Generated by Django 6.0 on 2026-01-10 11:55

import django.db.models.deletion
import src.utils.helpers
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(default=src.utils.helpers.random_token, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('createdBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('updatedBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.CharField(default=src.utils.helpers.random_token, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=15)),
                ('createdBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('updatedBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
    ]
