# Generated by Django 6.0 on 2026-02-09 23:54

import django.db.models.deletion
import src.utils.helpers
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="location",
        ),
        migrations.CreateModel(
            name="VendorLocation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=src.utils.helpers.random_token,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "displayName",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                ("state", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "houseNumber",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("road", models.CharField(blank=True, max_length=150, null=True)),
                ("town", models.CharField(blank=True, max_length=150, null=True)),
                ("suburb", models.CharField(blank=True, max_length=150, null=True)),
                ("district", models.CharField(blank=True, max_length=150, null=True)),
                ("country", models.CharField(blank=True, max_length=150, null=True)),
                ("processed", models.BooleanField(default=False)),
                (
                    "createdBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                (
                    "updatedBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now=True)),
                ("updatedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendors.vendor"
                    ),
                ),
            ],
        ),
    ]
