# Generated by Django 6.0 on 2026-02-11 02:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("10"), max_digits=25
            ),
        ),
        migrations.AlterField(
            model_name="vendorlocation",
            name="latitude",
            field=models.DecimalField(
                decimal_places=20, default=Decimal("0.00"), max_digits=25
            ),
        ),
        migrations.AlterField(
            model_name="vendorlocation",
            name="longitude",
            field=models.DecimalField(
                decimal_places=20, default=Decimal("0.00"), max_digits=25
            ),
        ),
    ]
