# Generated by Django 6.0 on 2026-02-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_remove_vendor_location_vendorlocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorlocation",
            name="processed",
        ),
    ]
