# Generated by Django 6.0 on 2026-02-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_remove_vendorlocation_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorlocation",
            name="captured",
            field=models.BooleanField(default=False),
        ),
    ]
