# Generated by Django 6.0 on 2026-02-10 17:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_vendorlocation_captured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorlocation",
            name="displayName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendorlocation",
            name="latitude",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="vendorlocation",
            name="longitude",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0.00"), max_digits=15
            ),
        ),
    ]
