# Generated by Django 6.0 on 2026-03-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0005_alter_vendorlocation_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorlocation",
            name="state",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
