# Generated by Django 6.0 on 2026-02-10 17:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0005_alter_vendorlocation_displayname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorlocation",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="vendorlocation",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0.00"), max_digits=15
            ),
        ),
    ]
