# Generated by Django 6.0 on 2026-03-09 14:36

import django.db.models.deletion
import src.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0006_alter_vendorlocation_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorRedeemToken",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=src.utils.helpers.random_token,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "redeemToken",
                    models.CharField(
                        default=src.utils.helpers.random_token, editable=False
                    ),
                ),
                (
                    "redeemOrderId",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "deliveryId",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "redeemNote",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("redeemed", models.BooleanField(default=False)),
                (
                    "createdBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                (
                    "updatedBy",
                    models.CharField(
                        blank=True, default="dev", max_length=150, null=True
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vendor Redeem Tokens",
                "ordering": ["createdAt"],
            },
        ),
    ]
