# Generated by Django 6.0 on 2026-01-30 06:33

import src.utils.helpers
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(default=src.utils.helpers.random_token, editable=False, primary_key=True, serialize=False)),
                ('displayName', models.CharField(blank=True, max_length=150, null=True)),
                ('latitude', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('town', models.CharField(blank=True, max_length=150, null=True)),
                ('suburb', models.CharField(blank=True, max_length=150, null=True)),
                ('houseNumber', models.CharField(blank=True, max_length=150, null=True)),
                ('road', models.CharField(blank=True, max_length=150, null=True)),
                ('createdBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('updatedBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=src.utils.helpers.random_token, editable=False, primary_key=True, serialize=False)),
                ('subtotal', models.IntegerField(default=1)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('createdBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('updatedBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(default=src.utils.helpers.random_token, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('createdBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('updatedBy', models.CharField(blank=True, default='dev', max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
