# Generated by Django 6.0 on 2026-02-16 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("users", "0001_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.customer"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="menuItem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vendors.menuitem"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="orderlocation",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
    ]
