# Generated by Django 6.0 on 2026-02-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="processed",
            new_name="captured",
        ),
    ]
