# Generated by Django 6.0 on 2026-01-30 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menuItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.menuitem'),
        ),
    ]
