# Generated by Django 6.0 on 2026-03-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_createdat_alter_order_updatedat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlocation",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GHAA", "Greater Accra"),
                    ("GHAF", "Ahafo"),
                    ("GHAH", "Ashanti"),
                    ("GHBE", "Bono East"),
                    ("GHBO", "Bono"),
                    ("GHCP", "Central"),
                    ("GHEP", "Eastern"),
                    ("GHNE", "North East"),
                    ("GHNP", "Northern"),
                    ("GHOT", "Oti"),
                    ("GHSV", "Savannah"),
                    ("GHTV", "Volta"),
                    ("GHUE", "Upper East"),
                    ("GHUW", "Upper West"),
                    ("GHWN", "Western North"),
                    ("GHWP", "Western"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
