# Generated by Django 6.0 on 2026-01-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='specialNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
