# Generated by Django 6.0 on 2026-02-11 01:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_processed_location_captured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                decimal_places=10, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                decimal_places=10, default=Decimal("0.00"), max_digits=15
            ),
        ),
    ]
