# Generated by Django 6.0 on 2026-03-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_orderlocation_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlocation",
            name="captureMethod",
            field=models.CharField(
                blank=True,
                choices=[("auto", "auto"), ("manual", "manual")],
                default="auto",
                max_length=150,
                null=True,
            ),
        ),
    ]
