# Generated by Django 6.0 on 2026-02-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_specialnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
