# Generated by Django 6.0 on 2026-02-11 02:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                decimal_places=20, default=Decimal("0.00"), max_digits=25
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                decimal_places=20, default=Decimal("0.00"), max_digits=25
            ),
        ),
    ]
