# Generated by Django 6.0 on 2026-03-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_orderlocation_capturemethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlocation",
            name="country",
            field=models.CharField(
                blank=True, default="Ghana", max_length=150, null=True
            ),
        ),
    ]
