# Generated by Django 6.0 on 2026-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="status",
            new_name="deliveryStatus",
        ),
        migrations.AddField(
            model_name="order",
            name="customerLocationCaptured",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="riderDispatched",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
