# Generated by Django 6.0 on 2026-02-08 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_location_location_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
