# Generated by Django 6.0 on 2026-02-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_rename_status_order_deliverystatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paymentConfirmed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
