# Generated by Django 6.0 on 2026-02-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_location_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='specialNotes',
        ),
        migrations.AddField(
            model_name='order',
            name='specialNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
