# Generated by Django 6.0 on 2026-02-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_paymentconfirmed"),
        ("users", "0002_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.customer"
            ),
        ),
    ]
