# Generated by Django 6.0 on 2026-03-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_orderlocation_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlocation",
            name="displayName",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
