# Generated by Django 6.0 on 2026-02-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_orderitem_specialnotes_order_specialnotes"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="menuItem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vendors.menuitem"
            ),
        ),
    ]
