# Generated by Django 6.0 on 2026-03-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_orderlocation_displayname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customerLocationCaptured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="deliveryStatus",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentConfirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="riderDispatched",
            field=models.BooleanField(default=False),
        ),
    ]
