# Generated by Django 6.0 on 2026-03-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_customerlocationcaptured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlocation",
            name="city",
            field=models.CharField(
                blank=True, default="Accra", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderlocation",
            name="state",
            field=models.CharField(
                blank=True, default="Greater Accra", max_length=150, null=True
            ),
        ),
    ]
