# Generated by Django 6.0 on 2026-02-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_orderitem_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="region",
            new_name="state",
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
